/** @format */

import Sidebar from "@/components/shared/Sidebar";
import "./globals.css";
import { ThemeProvider } from "@/lib/utils/ThemeContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body>
          <main className="bg-white dark:bg-zinc-900 min-h-screen">
            <Sidebar>{children}</Sidebar>
          </main>
        </body>
      </ThemeProvider>
    </html>
  );
}
